const fs = require('fs')
const s = fs.readFileSync('C:\\Users\\mikod\\OneDrive\\Desktop\\Rijeka\\frontend\\src\\components\\blotter\\TradeBookingWindow.jsx','utf8')
const i = s.indexOf('scenario')
console.log('First occurrence:', JSON.stringify(s.slice(i-20, i+60)))
const j = s.indexOf("label:'SCENARIO'")
console.log('Label at:', j, JSON.stringify(s.slice(j-20, j+40)))
const k = s.indexOf("label: 'SCENARIO'")
console.log('Label2 at:', k)
// Find all tab definitions
const tabs = s.indexOf('TABS')
console.log('TABS at:', tabs, JSON.stringify(s.slice(tabs, tabs+200)))
