const fs = require('fs')
const s = fs.readFileSync('C:\\Users\\mikod\\OneDrive\\Desktop\\Rijeka\\frontend\\src\\components\\blotter\\TradeBookingWindow.jsx','utf8')
const start = s.indexOf('function ScenarioTab(')
const end = s.indexOf('\nexport default function TradeBookingWindow(')
const tab = s.slice(start, end)
// Show the pills row and confirm bar section
const pillsIdx = tab.indexOf('Tenor pills row')
const confirmIdx = tab.indexOf('Confirm bar')
console.log('Tab length:', tab.length)
console.log('\n--- PILLS ROW ---')
console.log(tab.slice(pillsIdx, pillsIdx+200))
console.log('\n--- CONFIRM BAR ---')
console.log(tab.slice(confirmIdx, confirmIdx+100))
// Show draw function start
const drawIdx = tab.indexOf('const draw = ()')
console.log('\n--- DRAW START ---')
console.log(tab.slice(drawIdx, drawIdx+100))
